version: '3.7'
services:
  ml_svm:
    build: ./ml
    ports:
          - 50051:50051
    environment:
      GRPC_PORT: "50051"
  ml_svm2:
    build: ./ml
    ports:
          - 50052:50052
    environment:
      GRPC_PORT: "50052"
  server:
    build: ./server
    depends_on:
      - ml_svm
      - ml_svm2
    ports:
      - 8080:8080
    environment:
      GRPC_HOST: "ml_svm"
      GRPC_PORT: "50051"
      GRPC_HOST2: "ml_svm2"
      GRPC_PORT2: "50052"
      GO_PORT: "8080"
      
  
